# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_type', models.CharField(choices=[('science', 'science'), ('art', 'art')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Topic'),
        ),
    ]
