# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180323_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Topic'),
        ),
    ]
